services:
  mongo:
    image: mongo:latest
    container_name: et-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  
  app:
    image: dillontodd10/code:expense-tracker
    container_name: et-api
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
    env_file:
      - .env.dev
    depends_on:
      - mongo

volumes:
  mongo_data: