version: 2.1

parameters:
  run-tests:
    type: boolean
    default: true

jobs:
  test:
    docker:
      - image: cimg/base:current

    steps:
      - checkout
      - run:
          name: "Install Dependencies"
          command: "npm install"
      
      - run:
          name: "Run Tests"
          command: "npm run test"

workflows:
  unit-tests:
    when: << pipeline.parameters.run-tests >>
    jobs:
      - test