version: 2.1

parameters:
  run-tests:
    type: boolean
    default: true

jobs:
  test:
    working_directory: ~/code
    docker:
      - image: cimg/node:23.1.0
    steps:
      - checkout
      - run:
          name: "test working_directory"
          command: "pwd"
      - run:
          name: "test working_directory again"
          command: "cat .gitignore"
      - run:
          name: "Install Dependencies"
          command: "npm install"
      - run:
          name: "Run Tests"
          command: "npm run test"

workflows:
  unit-tests:
    when: << pipeline.parameters.run-tests >>
    jobs:
      - test